'use strict';

const CYLINDER_FACES = 16,
      MINIMUM_DISTANCE = 10,
      FIELD_OF_VIEW = 45 * Math.PI / 180,
      Z_NEAR = 1,
      Z_FAR = 1000,
      ANGLE_COORDINATES_SCALAR = Math.PI / 180,
      INITIAL_MOUSE_COORDINATES = [ 0, 0 ],
      INITIAL_ANGLE_COORDINATES = [ 0, Math.PI / 2 ];

module.exports = {
  Z_FAR: Z_FAR,
  Z_NEAR: Z_NEAR,
  FIELD_OF_VIEW: FIELD_OF_VIEW,
  CYLINDER_FACES: CYLINDER_FACES,
  MINIMUM_DISTANCE: MINIMUM_DISTANCE,
  ANGLE_COORDINATES_SCALAR: ANGLE_COORDINATES_SCALAR,
  INITIAL_MOUSE_COORDINATES: INITIAL_MOUSE_COORDINATES,
  INITIAL_ANGLE_COORDINATES: INITIAL_ANGLE_COORDINATES
};
