'use strict';

const Z_FAR = 1000,
      Z_NEAR = 1,
      MOUSE_UP = 'MOUSE_UP',
      MOUSE_DOWN = 'MOUSE_DOWN',
      MOUSE_MOVE = 'MOUSE_MOVE',
      MOUSE_WHEEL = 'MOUSE_WHEEL',
      DELTA_SCALAR = 1.25,
      INVERT_SCALAR = -1,
      ANGLES_SCALAR = 0.01,
      OFFSET_SCALAR = 0.25,
      SHIFT_KEY_CODE = 16,
      VERTICES_LENGTH = 3,
      MINIMUM_DISTANCE = 1,
      DEFAULT_MARGIN_OF_ERROR = 0.0000001,
      DEGREES_TO_RADIANS_SCALAR = Math.PI / 180,
      FIELD_OF_VIEW = 45 * DEGREES_TO_RADIANS_SCALAR;

module.exports = {
  Z_FAR,
  Z_NEAR,
  MOUSE_UP,
  MOUSE_DOWN,
  MOUSE_MOVE,
  MOUSE_WHEEL,
  DELTA_SCALAR,
  INVERT_SCALAR,
  ANGLES_SCALAR,
  OFFSET_SCALAR,
  SHIFT_KEY_CODE,
  VERTICES_LENGTH,
  MINIMUM_DISTANCE,
  DEFAULT_MARGIN_OF_ERROR,
  DEGREES_TO_RADIANS_SCALAR,
  FIELD_OF_VIEW
};
